spring.application.name=Sentinel
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}

logging.level.org.springframework.security=DEBUG

stripe.secret_key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=whsec_729f0429ee5f892abc3c42906677d8119383b5e5445a2c47096183b209d7010a

stripe.price.bronze=price_1TackXEY5f4uXkeD6QBMtvSU
stripe.price.silver=price_1TackEEY5f4uXkeDTqkVd41z
stripe.price.gold=price_1TacjpEY5f4uXkeDxVDy9fQF

app.frontend-url=http://localhost:5173